package modelo;
// Generated 13-feb-2019 13:08:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="country"
    ,catalog="sakila"
)
public class Country  implements java.io.Serializable {


     private short countryId;
     private String country;
     private Date lastUpdate;
     private Set cities = new HashSet(0);

    public Country() {
    }

	
    public Country(short countryId, String country, Date lastUpdate) {
        this.countryId = countryId;
        this.country = country;
        this.lastUpdate = lastUpdate;
    }
    public Country(short countryId, String country, Date lastUpdate, Set cities) {
       this.countryId = countryId;
       this.country = country;
       this.lastUpdate = lastUpdate;
       this.cities = cities;
    }
   
     @Id 

    
    @Column(name="country_id", unique=true, nullable=false)
    public short getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(short countryId) {
        this.countryId = countryId;
    }

    
    @Column(name="country", nullable=false, length=50)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update", nullable=false, length=26)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set getCities() {
        return this.cities;
    }
    
    public void setCities(Set cities) {
        this.cities = cities;
    }




}


